function normalizeLang(lang) {
  const s = (lang ?? 'en').toString().trim().toLowerCase();
  if (s === 'ta' || s === 'tamil') return 'ta';
  if (s === 'tl' || s === 'tanglish') return 'tl';
  return 'en';
}

function buildPrompt({ lang, chart, categories, overallLifePath }) {
  const langInstruction =
    lang === 'ta'
      ? 'Write in Tamil.'
      : lang === 'tl'
        ? 'Write in Tanglish (Tamil written using English letters).'
        : 'Write in English.';

  const categoryLines = Object.entries(categories).map(([key, v]) => {
    const score = v?.score ?? null;
    const keywords = Array.isArray(v?.keywords) ? v.keywords.join(', ') : '';
    const raw = v?.rawInterpretation ?? '';
    return { key, score, keywords, raw };
  });

  // Deterministic input for transparency; narrative itself is generated by Groq.
  return `
You are a skilled Jyotish astrologer and a careful technical writer.
${langInstruction}

Task:
Given the deterministic single-person Josiyam inputs below, produce:
1) An overall summary paragraph (4-6 sentences).
2) Short per-category explanations for all 20 categories (1-3 sentences each).

Rules:
- Output MUST be valid JSON only (no markdown, no backticks, no extra keys).
- Do not use random numbers.
- Keep each category text concise and directly tied to the provided deterministic raw interpretation.

Input chart:
${JSON.stringify(chart)}

Input categories (deterministic):
${JSON.stringify(categoryLines)}

Overall life path raw interpretation:
${JSON.stringify(overallLifePath)}

Return JSON schema:
{
  "language":"${lang}",
  "summary":"<overall paragraph>",
  "categories": {
    "<categoryKey>":"<short text>"
  }
}
`;
}

function extractJson(text) {
  if (!text) throw new Error('Empty Groq response');
  const s = String(text).trim();

  // Strip code fences if model returns them.
  const withoutFences = s
    .replace(/^```json\\s*/i, '')
    .replace(/^```\\s*/i, '')
    .replace(/```\\s*$/i, '');

  // Best-effort: extract outermost JSON object.
  const start = withoutFences.indexOf('{');
  const end = withoutFences.lastIndexOf('}');
  const candidate =
    start !== -1 && end !== -1 ? withoutFences.slice(start, end + 1) : withoutFences;

  return JSON.parse(candidate);
}

async function generateJosiyamNarrativeWithGroq({ lang, chart, categories, overallLifePath }) {
  const normalizedLang = normalizeLang(lang);

  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) return null; // Groq not configured

  const model = process.env.GROQ_CHAT_MODEL || 'llama-3.1-70b-versatile';

  const prompt = buildPrompt({ lang: normalizedLang, chart, categories, overallLifePath });

  const resp = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model,
      temperature: 0,
      max_tokens: 900,
      messages: [
        {
          role: 'system',
          content: 'You produce strict JSON. Follow the user schema exactly.',
        },
        {
          role: 'user',
          content: prompt,
        },
      ],
    }),
  });

  if (!resp.ok) {
    const text = await resp.text().catch(() => '');
    const err = new Error(`Groq request failed: ${resp.status} ${resp.statusText}`);
    err.groqBody = text;
    throw err;
  }

  const json = await resp.json();
  const content = json?.choices?.[0]?.message?.content;
  if (!content) return null;

  const parsed = extractJson(content);
  if (!parsed?.summary || !parsed?.categories) return null;

  return {
    includeNarrative: true,
    language: parsed.language || normalizedLang,
    summary: parsed.summary,
    categories: parsed.categories,
    cachedAt: new Date(),
  };
}

module.exports = {
  generateJosiyamNarrativeWithGroq,
};

